import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    name: v.string(),
    email: v.string(),
    passwordHash: v.string(),
    role: v.string(),
    phone: v.optional(v.string()),
    avatar: v.optional(v.string()),
    bio: v.optional(v.string()),
    blocked: v.optional(v.boolean()),
    blockedReason: v.optional(v.string()),
    verified: v.optional(v.boolean()),
    profileComplete: v.optional(v.boolean()),
    // Student fields
    academicClass: v.optional(v.string()),
    exam: v.optional(v.string()),
    marks: v.optional(v.string()),
    rank: v.optional(v.string()),
    interests: v.optional(v.array(v.string())),
    budget: v.optional(v.string()),
    preferredLocation: v.optional(v.string()),
    onboardingComplete: v.optional(v.boolean()),
    // Mentor fields
    college: v.optional(v.string()),
    course: v.optional(v.string()),
    branch: v.optional(v.string()),
    year: v.optional(v.string()),
    linkedin: v.optional(v.string()),
    approved: v.optional(v.boolean()),
    approvalStatus: v.optional(v.string()),
    onboardingStep: v.optional(v.number()),
    skills: v.optional(v.array(v.string())),
    pricing: v.optional(v.number()),
    pricing30: v.optional(v.number()),
    pricing60: v.optional(v.number()),
    availability: v.optional(v.array(v.string())),
    weeklySlots: v.optional(v.array(v.string())),
    rating: v.optional(v.number()),
    reviewsCount: v.optional(v.number()),
    sessionsCount: v.optional(v.number()),
    earnings: v.optional(v.number()),
    profileViews: v.optional(v.number()),
    responseTime: v.optional(v.string()),
    headline: v.optional(v.string()),
    about: v.optional(v.string()),
    whyBook: v.optional(v.string()),
    helpCategories: v.optional(v.array(v.string())),
    languages: v.optional(v.array(v.string())),
    sessionTypes: v.optional(v.array(v.string())),
    instantBooking: v.optional(v.boolean()),
    introVideo: v.optional(v.string()),
    socialLinks: v.optional(v.any()),
    achievements: v.optional(v.array(v.string())),
    internships: v.optional(v.array(v.string())),
    entranceExam: v.optional(v.string()),
    rankPercentile: v.optional(v.string()),
    cgpa: v.optional(v.string()),
    gender: v.optional(v.string()),
    city: v.optional(v.string()),
    state: v.optional(v.string()),
    degree: v.optional(v.string()),
    graduationYear: v.optional(v.string()),
    timezone: v.optional(v.string()),
    profilePhoto: v.optional(v.string()),
    termsAccepted: v.optional(v.boolean()),
    collegeIdUrl: v.optional(v.string()),
    submittedAt: v.optional(v.string()),
    qualification: v.optional(v.string()),
    experience: v.optional(v.string()),
    specialization: v.optional(v.array(v.string())),
    createdAt: v.optional(v.string()),
  }).index("by_email", ["email"]).index("by_role", ["role"]),

  colleges: defineTable({
    collegeId: v.string(),
    name: v.string(),
    shortName: v.string(),
    state: v.string(),
    city: v.string(),
    type: v.string(),
    nirfRank: v.optional(v.number()),
    established: v.optional(v.number()),
    annualFee: v.optional(v.string()),
    hostelFee: v.optional(v.string()),
    avgPackage: v.optional(v.string()),
    medianPackage: v.optional(v.string()),
    highestPackage: v.optional(v.string()),
    totalStudents: v.optional(v.number()),
    facultyCount: v.optional(v.number()),
    campusArea: v.optional(v.string()),
    website: v.optional(v.string()),
    branches: v.optional(v.array(v.string())),
    cutoffs: v.optional(v.any()),
    placements: v.optional(v.any()),
    highlights: v.optional(v.array(v.string())),
    counselling: v.optional(v.array(v.string())),
    imageUrl: v.optional(v.string()),
    description: v.optional(v.string()),
    createdAt: v.optional(v.string()),
  }).index("by_college_id", ["collegeId"]).index("by_state", ["state"]),

  sessions: defineTable({
    sessionId: v.string(),
    studentId: v.string(),
    studentName: v.string(),
    mentorId: v.string(),
    mentorName: v.string(),
    date: v.string(),
    timeSlot: v.string(),
    topic: v.string(),
    status: v.string(),
    price: v.number(),
    paymentId: v.optional(v.string()),
    duration: v.optional(v.number()),
    createdAt: v.string(),
  }).index("by_mentor", ["mentorId"]).index("by_student", ["studentId"]).index("by_session_id", ["sessionId"]),

  payments: defineTable({
    paymentId: v.string(),
    razorpayLinkId: v.optional(v.string()),
    shortUrl: v.optional(v.string()),
    amount: v.number(),
    currency: v.string(),
    status: v.string(),
    userId: v.string(),
    userName: v.string(),
    mentorId: v.string(),
    mentorName: v.string(),
    sessionId: v.optional(v.string()),
    createdAt: v.string(),
  }).index("by_payment_id", ["paymentId"]).index("by_user", ["userId"]).index("by_mentor", ["mentorId"]),

  reviews: defineTable({
    reviewId: v.string(),
    mentorId: v.string(),
    sessionId: v.optional(v.string()),
    reviewerId: v.string(),
    reviewerName: v.string(),
    rating: v.number(),
    comment: v.string(),
    createdAt: v.string(),
  }).index("by_mentor", ["mentorId"]).index("by_reviewer", ["reviewerId"]),

  batches: defineTable({
    batchId: v.string(),
    title: v.string(),
    description: v.string(),
    mentorId: v.string(),
    mentorName: v.string(),
    mentorCollege: v.optional(v.string()),
    maxStudents: v.number(),
    currentStudents: v.number(),
    price: v.number(),
    startDate: v.string(),
    endDate: v.string(),
    schedule: v.optional(v.string()),
    topics: v.optional(v.array(v.string())),
    students: v.optional(v.array(v.string())),
    status: v.string(),
    createdAt: v.string(),
  }).index("by_mentor", ["mentorId"]).index("by_batch_id", ["batchId"]),

  notifications: defineTable({
    notifId: v.string(),
    userId: v.string(),
    type: v.string(),
    title: v.string(),
    message: v.string(),
    read: v.boolean(),
    createdAt: v.string(),
  }).index("by_user", ["userId"]),

  chatHistory: defineTable({
    sessionId: v.string(),
    userId: v.string(),
    role: v.string(),
    content: v.string(),
    timestamp: v.string(),
  }).index("by_session", ["sessionId"]),

  counsellorApps: defineTable({
    appId: v.string(),
    name: v.string(),
    email: v.string(),
    phone: v.string(),
    qualification: v.string(),
    experience: v.string(),
    specialization: v.array(v.string()),
    bio: v.string(),
    status: v.string(),
    createdAt: v.string(),
  }).index("by_email", ["email"]).index("by_app_id", ["appId"]),

  postedSessions: defineTable({
    sessionId: v.string(),
    mentorId: v.string(),
    mentorName: v.string(),
    title: v.string(),
    description: v.string(),
    date: v.string(),
    timeSlot: v.string(),
    duration: v.number(),
    price: v.number(),
    topic: v.string(),
    maxStudents: v.number(),
    enrolledStudents: v.optional(v.array(v.string())),
    status: v.string(),
    createdAt: v.string(),
  }).index("by_mentor", ["mentorId"]).index("by_session_id", ["sessionId"]),

  withdrawals: defineTable({
    withdrawalId: v.string(),
    mentorId: v.string(),
    mentorName: v.string(),
    amount: v.number(),
    status: v.string(),
    createdAt: v.string(),
    approvedAt: v.optional(v.string()),
    rejectedAt: v.optional(v.string()),
  }).index("by_mentor", ["mentorId"]).index("by_withdrawal_id", ["withdrawalId"]),
});
